### ISSUE TITLE
Number of years of history in CPRD

### ISSUE THREAD

**Issue by rosap** [rOpenHealth/rEHR#19]
Count the number of years (or length of time) a patients has been in CPRD before entering the cohort (e.g. index date, study starts);
- (the length of time should include only when the practice is up to standard)

Note: Sometimes this information is needed to assure to capture incidence and not prevalence patients of e.g. psoriasis, diabetes, etc..

**Comment by DASpringate** [comment]
What is the best way to do this?
First consultation date  after UTS and CRD?
First clinical/referral event after UTS and CRD?

Both are easily done with the first_events() function.

This would fit in as an example in the vignette.

**Comment by evank23** [comment]
first either or just to be sure. I remember a very small percentage of
clincal info not making into the consultation files.

**Comment by DASpringate** [comment]
You mean events that don't have an associated consultation?

**Comment by evank23** [comment]
yep

**Comment by DASpringate** [comment]
This could mean rogue events just as easily as dodgy consultations...

**Comment by evank23** [comment]
what's your point?

**Comment by DASpringate** [comment]
Point is why trust the clinicals over the consultations?  It is simpler and less computationally intensive to go though just the consultation files in this case than to look at all of clinicals, referrals, therapies tests etc. and exclude the small percentage of unmatched events, since the error could go in either direction.

**Comment by evank23** [comment]
we don't know what's correct or wrong anyway so do you want to try to
define a valid first case?
or what looks like a first case?

if the latter then you get more cases in the clinical files. now why they
don't end up in consultations I have no clue and neither do CPRD.
might be worth looking into it for a subsample, maybe a practice, see what
% and what types of codes make it or not.

if ths issue is simplicity and speed, you will not really go wrong with
consultations but it seems a bit of a strange choice (at least to me)

**Comment by rosap** [comment]
Probably I didn't describe this properly. I just meant number of years prior registration. This is sometimes required when an incident cohort is selected in order to be more confident that patients are incident and not prevalent. 
E.g. the number of years prior registration would be the length of time between max(crd, uts) and e.g. The first event of a diagnosis, e.g. Psoriasis. In this case, it would be better to select the first event using clinical, referral, test, immunisation events rather than consultations. 
Do you both agree?

**Comment by rosap** [comment]
By the way, I'm not really sure this is an interesting "issue" to work on. You cans delete it if you prefer.

**Comment by evank23** [comment]
Yep agree that can make sense. There are many different ways to do
something like this so difficult to implement

**Comment by DASpringate** [comment]
Agreed, whatever way, it can easily be done with existing functions
