### ISSUE TITLE
Is this package still supported?

### ISSUE THREAD

**Issue by efratmuller** [rOpenHealth/rEHR#40]
I'm unable to install it unfortunately. I'm using R 3.1.2, the errors I'm getting are printed below. I wasn't able to find out what the exact problem is, I also shouldn't be having any trouble with rJava package (see one of the errors below) as it works fine for me in other places.
Is this package still supported at all? 
Any help would be much appreciated, Thanks!!

** install_github("rOpenHealth/rEHR")**
Downloading GitHub repo rOpenHealth/rEHR@master
from URL https://api.github.com/repos/rOpenHealth/rEHR/zipball/master
Installing rEHR
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/efratm/AppData/Local/Temp/RtmpUTTolg/devtools1c084fb675b6/rOpenHealth-rEHR-360872d" --library="C:/Users/efratm/Documents/R/win-library/3.1"  \
  --install-tests 

* installing *source* package 'rEHR' ...

It is recommended to use 'given' instead of 'middle'.

** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading

Warning: package 'DBI' was built under R version 3.1.3
Warning: package 'dplyr' was built under R version 3.1.3
Warning: replacing previous import by 'stringr::%>%' when loading 'rEHR'

** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Warning: package 'DBI' was built under R version 3.1.3
Warning: package 'dplyr' was built under R version 3.1.3
Warning: replacing previous import by 'stringr::%>%' when loading 'rEHR'
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
Execution halted
*** arch - x64
Warning: package 'DBI' was built under R version 3.1.3
Warning: package 'dplyr' was built under R version 3.1.3
Warning: replacing previous import by 'stringr::%>%' when loading 'rEHR'
Using CPRD settings
ERROR: loading failed for 'i386'
*removing 'C:/Users/efratm/Documents/R/win-library/3.1/rEHR'

Error: Command failed (1)

**Comment by evank23** [comment]
You need a previous R version. Should be available on CRAN very shortly
with these issues fixed.

**Comment by efratmuller** [comment]
Thank you!

**Comment by rosap** [comment]
Hi!
The package is working under the R development version at the moment
(future release R.4.0). It will hopefully be released on CRAN soon.
